#ifndef RTCMAKE_INIT_VERSION_H_
#define RTCMAKE_INIT_VERSION_H_

#define RTCMAKE_INIT_VERSION "1.0.0"

#define RTCMAKE_INIT_MAJOR_VERSION 1
#define RTCMAKE_INIT_MINOR_VERSION 0
#define RTCMAKE_INIT_PATCH_VERSION 0

#endif  // RTCMAKE_INIT_VERSION_H_
