name: build
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-24.04
    steps:      
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Compile
        run: cmake --build --preset release --target rtcmake_init

