name: build
on:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-24.04
    steps:   
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Cppcheck & clang-tidy
        run: |
          sudo apt-get install cppcheck
          sudo apt-get install clang-tidy

      - name: Configure 
        run: cmake --preset release
      
      - name: Build
        run: cmake --build --preset release --target rtcmake_init
